name-template: "v$NEXT_PATCH_VERSION"
tag-template: "v$NEXT_PATCH_VERSION"
categories:
    - title: "🚀 Features"
      labels: ["feature", "enhancement"]
    - title: "🐛 Fixes"
      labels: ["fix", "bug"]
    - title: "🧹 Chores"
      labels: ["chore"]
    - title: "📖 Docs"
      labels: ["docs"]
change-template: "- $TITLE (#$NUMBER) by @$AUTHOR"
change-title-escapes: '\<*_&' # keep markdown clean
no-changes-template: "- No notable changes"
template: |
    ## Changes since $PREVIOUS_TAG
    $CHANGES
