name: CI Checks

on:
    pull_request:

jobs:
    lint-and-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - run: npm install
            - run: npm run lint --if-present
            - run: npm run build --if-present
            - run: npm test --if-present
