name: Docs Sync

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    docs:
        runs-on: ubuntu-latest
        permissions:
            contents: write # Required for pushing

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Configure Git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"

            - name: Sync docs
              run: |
                  mkdir -p .tracking/changelogs
                  SNAPSHOT_ID=$(git rev-parse --short HEAD)
                  cp Changelog.md ".tracking/changelogs/Changelog#${SNAPSHOT_ID}.md"

            - name: Commit and push changes
              run: |
                  git add .
                  if git diff --staged --quiet; then
                    echo "No changes to commit"
                  else
                    git commit -m "docs: sync changelog snapshot ($(git rev-parse --short HEAD))"
                    git push origin HEAD:main
                  fi
