name: Docs Sync

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    docs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Configure Git
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@users.noreply.github.com"

            - name: Sync docs
              run: |
                  mkdir -p .tracking/changelogs
                  SNAPSHOT_ID=$(git rev-parse --short HEAD)
                  cp Changelog.md ".tracking/changelogs/Changelog#${SNAPSHOT_ID}.md"

            - name: Commit changes
              run: |
                  git add .
                  git commit -m "docs: sync changelog snapshot ($(git rev-parse --short HEAD))" || echo "No changes to commit"

            - name: Push changes with PAT
              run: |
                  git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
