name: Docs Sync

on:
    push:
        branches:
            - main
        paths:
            - "Changelog.md"
    workflow_dispatch:

concurrency:
    group: docs-sync
    cancel-in-progress: false

jobs:
    docs:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  fetch-depth: 0

            - name: Configure Git
              run: |
                  git config user.name "github-actions[bot]"
                  git config user.email "github-actions[bot]@users.noreply.github.com"
                  git fetch origin main

            - name: Sync docs
              run: |
                  mkdir -p .tracking/changelogs

                  # Read counter or initialize to 1
                  COUNTER_FILE=".tracking/.changelog_counter"
                  if [ -f "$COUNTER_FILE" ]; then
                    NEXT_NUM=$(cat "$COUNTER_FILE")
                  else
                    NEXT_NUM=1
                  fi

                  # Copy changelog with sequential number
                  cp Changelog.md ".tracking/changelogs/Changelog#${NEXT_NUM}.md"

                  # Increment counter
                  echo $((NEXT_NUM + 1)) > "$COUNTER_FILE"

            - name: Commit and push changes
              run: |
                  git add .tracking/
                  if git diff --staged --quiet; then
                    echo "No changes to commit"
                  else
                    CURRENT_NUM=$(cat .tracking/.changelog_counter)
                    git commit -m "docs: sync changelog snapshot #$((CURRENT_NUM - 1))"
                    
                    # Pull and rebase before pushing to avoid conflicts
                    git pull --rebase origin main || true
                    git push origin HEAD:main
                  fi
