name: Release to Changelog

on:
    release:
        types: [published]

jobs:
    update-changelog:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
              with:
                  persist-credentials: false

            - name: Configure Git
              run: |
                  git config user.name "github-actions"
                  git config user.email "github-actions@users.noreply.github.com"

            - name: Update changelog
              run: |
                  echo "## $(date -u)" >> Changelog.md
                  echo "" >> Changelog.md
                  echo "Release $GITHUB_REF_NAME" >> Changelog.md
                  echo "" >> Changelog.md

            - name: Commit changes
              run: |
                  git add Changelog.md
                  git commit -m "docs: update changelog for $GITHUB_REF_NAME" || echo "No changes to commit"

            - name: Push changes with PAT
              run: |
                  git push https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }} HEAD:main
