name: Update Tracking Docs

on:
    push:
        branches: [main]
        paths-ignore:
            - "Changelog.md"
            - "Todo.md"
    issues:
        types: [opened, closed, reopened, labeled, unlabeled, edited]

permissions:
    contents: write
    pull-requests: write
    issues: read

jobs:
    update-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Install GH CLI and jq
              run: |
                  sudo apt-get update
                  sudo apt-get install -y gh jq

            - name: Collect Issues
              env:
                  GH_TOKEN: ${{ secrets.GH_PAT }}
              run: |
                  OWNER=${{ github.repository_owner }}
                  REPO=${{ github.event.repository.name }}

                  # Fetch both open and closed issues
                  gh api repos/$OWNER/$REPO/issues --paginate -f state=all \
                    --jq '[.[] | {number, title, state, url: .html_url, labels: [.labels[].name], closed_at, created_at}]' > issues.json

                  # Debug: show what we got
                  echo "Total issues fetched: $(jq 'length' issues.json)"
                  echo "Open issues: $(jq '[.[] | select(.state == "open")] | length' issues.json)"
                  echo "Closed issues: $(jq '[.[] | select(.state == "closed")] | length' issues.json)"

            - name: Make script executable
              run: chmod +x .github/scripts/update-docs.sh

            - name: Generate docs (script)
              run: ./.github/scripts/update-docs.sh

            - name: Create Pull Request
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GH_PAT }}
                  branch: tracking-updates
                  commit-message: "docs: update tracking documentation"
                  title: "Update Tracking Documentation"
                  body: |
                      Automated documentation update

                      Updated files:
                      - Changelog.md
                      - Todo.md
                  add-paths: |
                      Changelog.md
                      Todo.md
