name: Update Tracking Docs

on:
    push:
        branches: [main]
        paths-ignore:
            - "Changelog.md"
            - "Todo.md"
    issues:
        types: [opened, closed, reopened, labeled, unlabeled, edited]

permissions:
    contents: write
    pull-requests: write
    issues: read

jobs:
    update-docs:
        runs-on: ubuntu-latest
        steps:
            # --- Checkout repo ---
            - uses: actions/checkout@v4

            # --- Install GH CLI and jq ---
            - name: Install GH CLI and jq
              run: |
                  sudo apt-get update
                  sudo apt-get install -y gh jq

            # --- Collect Issues ---
            - name: Collect Issues
              env:
                  GH_TOKEN: ${{ secrets.GH_PAT }}
              run: |
                  OWNER=$(echo $GITHUB_REPOSITORY | cut -d'/' -f1)
                  REPO=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)

                  gh api repos/$OWNER/$REPO/issues?state=all --paginate \
                    --jq '[.[] | {number, title, state, url: .html_url, labels: [.labels[].name], closed_at, created_at}]' \
                    > issues.json

            # --- Make script executable ---
            - name: Make script executable
              run: chmod +x .github/scripts/update-docs.sh

            # --- Generate docs ---
            - name: Generate docs (script)
              run: ./.github/scripts/update-docs.sh

            # --- Check for changes ---
            - name: Check for changes
              id: git-check
              run: |
                  git add Changelog.md Todo.md
                  if git diff --cached --quiet; then
                    echo "No changes to commit"
                    echo "changes=false" >> $GITHUB_OUTPUT
                  else
                    echo "Changes detected"
                    echo "changes=true" >> $GITHUB_OUTPUT
                  fi

            # --- Debug: show what will be committed ---
            - name: Debug changes to be committed
              if: steps.git-check.outputs.changes == 'true'
              run: |
                  echo "=== Git status ==="
                  git status
                  echo "=== Git diff ==="
                  git diff --cached

            # --- Force-update the branch only if changes exist ---
            - name: Force-update tracking branch
              if: steps.git-check.outputs.changes == 'true'
              run: |
                  git checkout -B tracking-updates
                  git commit -m "docs: update tracking documentation" || echo "No changes to commit"
                  git push origin tracking-updates --force

            # --- Create Pull Request only if changes exist ---
            - name: Create Pull Request
              if: steps.git-check.outputs.changes == 'true'
              uses: peter-evans/create-pull-request@v6
              with:
                  token: ${{ secrets.GH_PAT }}
                  branch: tracking-updates
                  base: main
                  commit-message: "docs: update tracking documentation"
                  title: "Update Tracking Documentation"
                  body: |
                      Automated documentation update

                      Updated files:
                      - Changelog.md
                      - Todo.md
                  add-paths: |
                      Changelog.md
                      Todo.md
